#!/bin/csh

# 检查参数是否正确
if ($#argv != 1) then
    echo "usage: $0 <elf/file/path>"
    exit 1
endif

set qemu_path = "/tools/software/qemu/bin/qemu-riscv32"

set full_command = "$qemu_path $1"

eval $full_command


#set script_path = `readlink -f $0`
#set script_dir  = `dirname $script_path`

#echo "Script path: $script_dir"

#set trace_translate_command = "python $script_dir/qemu_trace_translate.py $1.qtoy.trace.raw $1.qtoy.trace"
# 执行命令

#eval $trace_translate_command
