#!/bin/csh

# 检查参数是否正确
if ($#argv != 1) then
    echo "usage: $0 <elf/file/path>"
    exit 1
endif

# 设置QEMU路径和其他参数
set qemu_path = "/home/liuyunqi/trees/qemu/build/qemu-system-riscv32"
set qemu_args = "-nographic -m 2048 -smp 1 -M scalar_toy"
set trace_args = " -accel tcg,one-insn-per-tb=on -d cpu,exec"
#set trace_args = ""
#set log_args = "-D log%d"
set log_args = "-D $1.qtoy.trace.raw"
set device_args = "-device loader,cpu-num=0,file=$1"

# 构建完整的命令
set full_command = "$qemu_path $qemu_args $log_args $trace_args $device_args"

#echo "$0"

set script_path = `readlink -f $0`
set script_dir  = `dirname $script_path`

#echo "Script path: $script_dir"

set trace_translate_command = "python $script_dir/qemu_trace_translate.py $1.qtoy.trace.raw $1.qtoy.trace"
# 执行命令

#echo $full_command
eval $full_command

eval $trace_translate_command
